// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type TrackItem struct {
	Time     string `json:"time"`
	Status   string `json:"status"`
	Location string `json:"location"`
}

type TrackRequest struct {
	TrackNo string `json:"trackNo"`
}

type TrackResponse struct {
	TrackNo    string      `json:"trackNo"`
	Carrier    string      `json:"carrier"`
	StatusList []TrackItem `json:"statusList"`
	Raw        string      `json:"raw,omitempty"`
}
