// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"coupang_spider/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/seven/track",
				Handler: SevenTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/familymart/track",
				Handler: FamilyMartTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hilife/track",
				Handler: HiLifeTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/okmart/track",
				Handler: OkMartTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kerry/track",
				Handler: KerryTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/spx/track",
				Handler: SpxTrackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/spider/v1"),
	)
}

// TW_HILIFE：6G8927076806
//TW_‌7ELEVEN：R19277331533
//TW_OKMART：68395229080
//TW_FAMILYMART：16336622686
//TW_SPX：TW265078969514F
//TW_KERRY：40509145237
//-------------------------------------
//TW_ECAN
//TW_HCT
//TW_TCAT