// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"coupang_spider/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/familymart/track",
				Handler: FamilymartTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/hilife/track",
				Handler: HilifeTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/kerry/track",
				Handler: KerryTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/okmart/track",
				Handler: OkmartTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/seven/track",
				Handler: SevenTrackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/spx/track",
				Handler: SpxTrackHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/spider/v1"),
	)
}
